
# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: myapp.com
    CA:
        Country: ES
        Province: Madrid
        Locality: Madrid
    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: orderer0
      - Hostname: orderer1
      - Hostname: orderer2
    
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Org1
  # ---------------------------------------------------------------------------
  - Name: netflix
    Domain: netflix.myapp.com
    EnableNodeOUs: true
    CA:
      Country: ES
      Province: Madrid
      Locality: Madrid
    Template:
      Count: 1
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # Org2: See "Org1" for full specification
  # ---------------------------------------------------------------------------
  - Name: hbo
    Domain: hbo.myapp.com
    EnableNodeOUs: true
    CA:
        Country: ES
        Province: Madrid
        Locality: Madrid
    Template:
      Count: 1
    Users:
      Count: 1
    
