# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:




  peer0.netflix.myapp.com:
    container_name: peer0.netflix.myapp.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.netflix.myapp.com
      - CORE_PEER_ADDRESS=peer0.netflix.myapp.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.netflix.myapp.com:7051
      - CORE_PEER_LOCALMSPID=netflixMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/netflix.myapp.com/peers/peer0.netflix.myapp.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/netflix.myapp.com/peers/peer0.netflix.myapp.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7052:7052
      - 7053:7053

  peer0.hbo.myapp.com:
    container_name: peer0.hbo.myapp.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.hbo.myapp.com
      - CORE_PEER_ADDRESS=peer0.hbo.myapp.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.hbo.myapp.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.hbo.myapp.com:8051
      - CORE_PEER_LOCALMSPID=hboMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/hbo.myapp.com/peers/peer0.hbo.myapp.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/hbo.myapp.com/peers/peer0.hbo.myapp.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 8051:7051
      - 8052:7052
      - 8053:7053